insert into public.roster (match_label, team, squad_number, player_name, position) values
  ('2026 FIFA World Cup Final', 'Spain', 1, 'David Raya', 'GK'),
  ('2026 FIFA World Cup Final', 'Spain', 2, 'Marc Pubill', 'DF'),
  ('2026 FIFA World Cup Final', 'Spain', 3, 'Alejandro Grimaldo', 'DF'),
  ('2026 FIFA World Cup Final', 'Spain', 4, 'Eric García', 'DF'),
  ('2026 FIFA World Cup Final', 'Spain', 5, 'Marcos Llorente', 'DF'),
  ('2026 FIFA World Cup Final', 'Spain', 6, 'Mikel Merino', 'MF'),
  ('2026 FIFA World Cup Final', 'Spain', 7, 'Ferran Torres', 'FW'),
  ('2026 FIFA World Cup Final', 'Spain', 8, 'Fabián Ruiz', 'MF'),
  ('2026 FIFA World Cup Final', 'Spain', 9, 'Gavi', 'MF'),
  ('2026 FIFA World Cup Final', 'Spain', 10, 'Dani Olmo', 'MF'),
  ('2026 FIFA World Cup Final', 'Spain', 11, 'Yeremi Pino', 'FW'),
  ('2026 FIFA World Cup Final', 'Spain', 12, 'Pedro Porro', 'DF'),
  ('2026 FIFA World Cup Final', 'Spain', 13, 'Joan García', 'GK'),
  ('2026 FIFA World Cup Final', 'Spain', 14, 'Aymeric Laporte', 'DF'),
  ('2026 FIFA World Cup Final', 'Spain', 15, 'Álex Baena', 'MF'),
  ('2026 FIFA World Cup Final', 'Spain', 16, 'Rodri', 'MF'),
  ('2026 FIFA World Cup Final', 'Spain', 17, 'Nico Williams', 'FW'),
  ('2026 FIFA World Cup Final', 'Spain', 18, 'Martin Zubimendi', 'MF'),
  ('2026 FIFA World Cup Final', 'Spain', 19, 'Lamine Yamal', 'FW'),
  ('2026 FIFA World Cup Final', 'Spain', 20, 'Pedri', 'MF'),
  ('2026 FIFA World Cup Final', 'Spain', 21, 'Mikel Oyarzabal', 'FW'),
  ('2026 FIFA World Cup Final', 'Spain', 22, 'Pau Cubarsí', 'DF'),
  ('2026 FIFA World Cup Final', 'Spain', 23, 'Unai Simón', 'GK'),
  ('2026 FIFA World Cup Final', 'Spain', 24, 'Marc Cucurella', 'DF'),
  ('2026 FIFA World Cup Final', 'Spain', 25, 'Víctor Muñoz', 'FW'),
  ('2026 FIFA World Cup Final', 'Spain', 26, 'Borja Iglesias', 'FW'),
  ('2026 FIFA World Cup Final', 'Argentina', 1, 'Juan Musso', 'GK'),
  ('2026 FIFA World Cup Final', 'Argentina', 2, 'Leonardo Balerdi', 'DF'),
  ('2026 FIFA World Cup Final', 'Argentina', 3, 'Nicolás Tagliafico', 'DF'),
  ('2026 FIFA World Cup Final', 'Argentina', 4, 'Gonzalo Montiel', 'DF'),
  ('2026 FIFA World Cup Final', 'Argentina', 5, 'Leandro Paredes', 'MF'),
  ('2026 FIFA World Cup Final', 'Argentina', 6, 'Lisandro Martínez', 'DF'),
  ('2026 FIFA World Cup Final', 'Argentina', 7, 'Rodrigo De Paul', 'MF'),
  ('2026 FIFA World Cup Final', 'Argentina', 8, 'Valentín Barco', 'MF'),
  ('2026 FIFA World Cup Final', 'Argentina', 9, 'Julián Álvarez', 'FW'),
  ('2026 FIFA World Cup Final', 'Argentina', 10, 'Lionel Messi', 'FW'),
  ('2026 FIFA World Cup Final', 'Argentina', 11, 'Giovani Lo Celso', 'MF'),
  ('2026 FIFA World Cup Final', 'Argentina', 12, 'Gerónimo Rulli', 'GK'),
  ('2026 FIFA World Cup Final', 'Argentina', 13, 'Cristian Romero', 'DF'),
  ('2026 FIFA World Cup Final', 'Argentina', 14, 'Exequiel Palacios', 'MF'),
  ('2026 FIFA World Cup Final', 'Argentina', 15, 'Nicolás González', 'FW'),
  ('2026 FIFA World Cup Final', 'Argentina', 16, 'Thiago Almada', 'FW'),
  ('2026 FIFA World Cup Final', 'Argentina', 17, 'Giuliano Simeone', 'FW'),
  ('2026 FIFA World Cup Final', 'Argentina', 18, 'Nico Paz', 'FW'),
  ('2026 FIFA World Cup Final', 'Argentina', 19, 'Nicolás Otamendi', 'DF'),
  ('2026 FIFA World Cup Final', 'Argentina', 20, 'Alexis Mac Allister', 'MF'),
  ('2026 FIFA World Cup Final', 'Argentina', 21, 'José Manuel López', 'FW'),
  ('2026 FIFA World Cup Final', 'Argentina', 22, 'Lautaro Martínez', 'FW'),
  ('2026 FIFA World Cup Final', 'Argentina', 23, 'Emiliano Martínez', 'GK'),
  ('2026 FIFA World Cup Final', 'Argentina', 24, 'Enzo Fernández', 'MF'),
  ('2026 FIFA World Cup Final', 'Argentina', 25, 'Facundo Medina', 'DF'),
  ('2026 FIFA World Cup Final', 'Argentina', 26, 'Nahuel Molina', 'DF')
on conflict (match_label, team, squad_number) do update set
  player_name = excluded.player_name,
  position = excluded.position;
